# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "bibtex-ruby", "~> 6.0"
gem "facets", "~> 3.1"
gem "pandoc-ruby", "~> 2.1"
gem "activerecord", "~> 7.0"
